# Generated by Django 4.1.7 on 2023-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FasalUdyog_Website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="stock_center",
            name="item_id",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="stock_center",
            name="msp",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="stock_center",
            name="quantity",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="stock_total",
            name="item_id",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="stock_total",
            name="msp",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="stock_total",
            name="quantity",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="store_has_orders",
            name="order_id",
            field=models.CharField(max_length=45),
        ),
    ]
